version: '2.1'
services:
  container1:
    build:
      context: ./
      dockerfile: flask1.Dockerfile
    container_name: flask1
    environment:
      FLASK2_HOST : "http://flask2:5002"
    image: flask1
    hostname: flask1
    ports:
      - "5001:5001"
  container2:
    build:
      context: ./
      dockerfile: flask2.Dockerfile
    container_name: flask2
    image: flask2
    hostname: flask2
    ports:
      - "5002:5002"
